= Vertx unit

Asynchronous polyglot unit testing.

== Introduction

Vertx Unit aims to make Vertx applications testable. It provides a polyglot API for writing asynchronous
tests easily. Vertx Unit Api borrows from existing test frameworks like http://junit.org[JUnit] or http://qunitjs.com[QUnit]
and follows the Vert.x practices.

Vertx Unit can be used in different ways and run anywhere your code runs, it is just a matter of reporting
the results the right way, this example shows the bare minimum test suite:

[source,js]
----
var TestSuite = require("vertx-unit-js/test_suite");
var suite = TestSuite.create("the_test_suite");
suite.test("my_test", function (test) {
  var s = "value";
  test.assertEquals("value", s);
});
suite.run();

----

The  method will execute the suite and go through all the
tests of the suite. The suite can fail or pass, this does not matter if the outter world is not aware
of the test result.

[source,js]
----
var TestSuite = require("vertx-unit-js/test_suite");
var suite = TestSuite.create("the_test_suite");
suite.test("my_test", function (test) {
  var s = "value";
  test.assertEquals("value", s);
});
suite.run({
  "reporters" : [
    {
      "to" : "console"
    }
  ]
});

----

When executed, the test suite now reports to the console the steps of the test suite:

----
Begin test suite the_test_suite
Begin test my_test
Passed my_test
End test suite the_test_suite , run: 1, Failures: 0, Errors: 0
----

The  option configures the reporters used by the suite runner for reporting the execution
of the tests, see the <<reporting>> section for more info.

== Writing a test suite

A test suite is a named collection of test case, a test case is a straight callback to execute. The suite can
have lifecycle callbacks to execute _before_ and/or _after_ the test cases or the test suite that are used for
initializing or disposing services used by the test suite.

[source,js]
----
var TestSuite = require("vertx-unit-js/test_suite");
var suite = TestSuite.create("the_test_suite");
suite.test("my_test_1", function (test) {
  // Test 1
});
suite.test("my_test_2", function (test) {
  // Test 2
});
suite.test("my_test_3", function (test) {
  // Test 3
});

----

The API is fluent and therefore the test can be chained:

[source,js]
----
var TestSuite = require("vertx-unit-js/test_suite");
var suite = TestSuite.create("the_test_suite");
suite.test("my_test_1", function (test) {
  // Test 1
}).test("my_test_2", function (test) {
  // Test 2
}).test("my_test_3", function (test) {
  // Test 3
});

----

Vertx Unit provides _before_ and _after_ callbacks for doing global setup or cleanup:

[source,js]
----
var TestSuite = require("vertx-unit-js/test_suite");
var suite = TestSuite.create("the_test_suite");
suite.before(function (test) {
  // Test suite setup
}).test("my_test_1", function (test) {
  // Test 1
}).test("my_test_2", function (test) {
  // Test 2
}).test("my_test_3", function (test) {
  // Test 3
}).after(function (test) {
  // Test suite cleanup
});

----

The declaration order of the method does not matter, the example declares the _before_ callback before
the test cases and _after_ callback after the test cases but it could be anywhere, as long as it is done before
running the test suite.

The _before_ callback is executed before any tests, when it fails, the test suite execution will stop and the
failure is reported. The _after_ callback is the last callback executed by the testsuite, unless
the _before_ callback reporter a failure.

Likewise, Vertx Unit provides the _beforeEach_ and _afterEach_ callback that do the same but are executed
for each test case:

[source,js]
----
var TestSuite = require("vertx-unit-js/test_suite");
var suite = TestSuite.create("the_test_suite");
suite.beforeEach(function (test) {
  // Test case setup
}).test("my_test_1", function (test) {
  // Test 1
}).test("my_test_2", function (test) {
  // Test 2
}).test("my_test_3", function (test) {
  // Test 3
}).afterEach(function (test) {
  // Test case cleanup
});

----

The _beforeEach_ callback is executed before each test case, when it fails, the test case is not executed and the
failure is reported. The _afterEach_ callback is the executed just after the test case callback, unless
the _beforeEach_ callback reported a failure.

== Asserting

Vertx Unit provides the _test_ object for doing assertions in test cases. The _test_ object provides the usual
methods when dealing with assertions.

=== assertEquals

Assert two objects are equals, works for _basic_ types or _json_ types.

[source,js]
----
suite.test("my_test_1", function (test) {
  test.assertEquals(10, callbackCount);
});

----

There is also an overloaded version for providing a message:

[source,js]
----
suite.test("my_test_1", function (test) {
  test.assertEquals(10, callbackCount, "Should have been 10 instead of " + callbackCount);
});

----

Usually each assertion provides an overloaded version.

=== assertNotEquals

The counter part of _assertEquals_.

[source,js]
----
suite.test("my_test_1", function (test) {
  test.assertNotEquals(10, callbackCount);
});

----

=== assertTrue and assertFalse

Asserts the value of a boolean expression.

[source,js]
----
suite.test("my_test_1", function (test) {
  test.assertTrue(var);
  test.assertFalse(value > 10);
});

----

=== Failing

Last but not least, _test_ provides a _fail_ method that will throw an assertion error:

[source,js]
----
suite.test("my_test_1", function (test) {
  test.fail("That should never happen");
  // Following statements won't be executed
});

----

== Asynchronous testing

todo

[[reporting]]
== Reporting

todo

== Junit integration

todo