= Vertx unit

Asynchronous polyglot unit testing.

== Introduction

Vertx Unit is designed for writing asynchronous unit tests with a polyglot API and running these tests
in the JVM. Vertx Unit Api borrows from existing test frameworks like http://junit.org[JUnit] or http://qunitjs.com[QUnit]
and follows the Vert.x practices.

As a consequence Vertx Unit is the natural choice for testing Vert.x applications.

It can be used in different ways and run anywhere your code runs, it is just a matter of reporting
the results the right way, this example shows the bare minimum test suite:

[source,java]
----
TestSuite suite = TestSuite.create("the_test_suite");
suite.test("my_test_case", context -> {
  String s = "value";
  context.assertEquals("value", s);
});
suite.run();
----

The  method will execute the suite and go through all the
tests of the suite. The suite can fail or pass, this does not matter if the outer world is not aware
of the test result.

[source,java]
----
TestSuite suite = TestSuite.create("the_test_suite");
suite.test("my_test_case", context -> {
  String s = "value";
  context.assertEquals("value", s);
});
suite.run(new TestOptions().addReporter(new ReportOptions().setTo("console")));
----

When executed, the test suite now reports to the console the steps of the test suite:

----
Begin test suite the_test_suite
Begin test my_test
Passed my_test
End test suite the_test_suite , run: 1, Failures: 0, Errors: 0
----

The  option configures the reporters used by the suite runner for reporting the execution
of the tests, see the <<reporting>> section for more info.

== Writing a test suite

A test suite is a named collection of test case, a test case is a straight callback to execute. The suite can
have lifecycle callbacks to execute _before_ and/or _after_ the test cases or the test suite that are used for
initializing or disposing services used by the test suite.

[source,java]
----
TestSuite suite = TestSuite.create("the_test_suite");
suite.test("my_test_case_1", context -> {
  // Test 1
});
suite.test("my_test_case_2", context -> {
  // Test 2
});
suite.test("my_test_case_3", context -> {
  // Test 3
});
----

The API is fluent and therefore the test cases can be chained:

[source,java]
----
TestSuite suite = TestSuite.create("the_test_suite");
suite.test("my_test_case_1", context -> {
  // Test 1
}).test("my_test_case_2", context -> {
  // Test 2
}).test("my_test_case_3", context -> {
  // Test 3
});
----

The test cases declaration order is not guaranteed, so test cases should not rely on the execution of
another test case to run. Such practice is considered as a bad one.

Vertx Unit provides _before_ and _after_ callbacks for doing global setup or cleanup:

[source,java]
----
TestSuite suite = TestSuite.create("the_test_suite");
suite.before(context -> {
  // Test suite setup
}).test("my_test_case_1", context -> {
  // Test 1
}).test("my_test_case_2", context -> {
  // Test 2
}).test("my_test_case_3", context -> {
  // Test 3
}).after(context -> {
  // Test suite cleanup
});
----

The declaration order of the method does not matter, the example declares the _before_ callback before
the test cases and _after_ callback after the test cases but it could be anywhere, as long as it is done before
running the test suite.

The _before_ callback is executed before any tests, when it fails, the test suite execution will stop and the
failure is reported. The _after_ callback is the last callback executed by the testsuite, unless
the _before_ callback reporter a failure.

Likewise, Vertx Unit provides the _beforeEach_ and _afterEach_ callback that do the same but are executed
for each test case:

[source,java]
----
TestSuite suite = TestSuite.create("the_test_suite");
suite.beforeEach(context -> {
  // Test case setup
}).test("my_test_case_1", context -> {
  // Test 1
}).test("my_test_case_2", context -> {
  // Test 2
}).test("my_test_case_3", context -> {
  // Test 3
}).afterEach(context -> {
  // Test case cleanup
});
----

The _beforeEach_ callback is executed before each test case, when it fails, the test case is not executed and the
failure is reported. The _afterEach_ callback is the executed just after the test case callback, unless
the _beforeEach_ callback reported a failure.

== Asserting

Vertx Unit provides the _test_ object for doing assertions in test cases. The _test_ object provides the usual
methods when dealing with assertions.

=== assertEquals

Assert two objects are equals, works for _basic_ types or _json_ types.

[source,java]
----
suite.test("my_test_case", context -> {
  context.assertEquals(10, callbackCount);
});
----

There is also an overloaded version for providing a message:

[source,java]
----
suite.test("my_test_case", context -> {
  context.assertEquals(10, callbackCount, "Should have been 10 instead of " + callbackCount);
});
----

Usually each assertion provides an overloaded version.

=== assertNotEquals

The counter part of _assertEquals_.

[source,java]
----
suite.test("my_test_case", context -> {
  context.assertNotEquals(10, callbackCount);
});
----

=== assertTrue and assertFalse

Asserts the value of a boolean expression.

[source,java]
----
suite.test("my_test_case", context -> {
  context.assertTrue(var);
  context.assertFalse(value > 10);
});
----

=== Failing

Last but not least, _test_ provides a _fail_ method that will throw an assertion error:

[source,java]
----
suite.test("my_test_case", context -> {
  context.fail("That should never happen");
  // Following statements won't be executed
});
----

== Asynchronous testing

The previous examples supposed that test cases were terminated after their respective callbacks, this is the
default behavior of a test case callback. Often it is desirable to terminate the test after the test case
callback, for instance:

.The Async object asynchronously completes the test case
[source,java]
----
suite.test("my_test_case", context -> {
  Async async = context.async();
  eventBus.consumer("the-address", msg -> {
    // <2>
    async.complete();
  });
  // <1>
});
----
<1> The callback exits but the test case is not terminated
<2> The event callback from the bus terminates the test

Creating an `link:apidocs/io/vertx/ext/unit/Async.html[Async]` object with the `link:apidocs/io/vertx/ext/unit/TestContext.html#async--[async]` method marks the
executed test case as non terminated. The test case terminates when the `link:apidocs/io/vertx/ext/unit/Async.html#complete--[complete]`
method is invoked.

NOTE: When the `complete` callback is not invoked, the test case fails after a certain timeout.

Several `Async` objects can be created during the same test case, all of them must be _completed_ to terminate
the test.

.Several Async objects provide coordination
[source,java]
----
suite.test("my_test_case", context -> {

  Async async1 = context.async();
  HttpClient client = vertx.createHttpClient();
  HttpClientRequest req = client.get(8080, "localhost", "/");
  req.exceptionHandler(err -> context.fail(err.getMessage()));
  req.handler(resp -> {
    context.assertEquals(200, resp.statusCode());
    async1.complete();
  });
  req.end();

  Async async2 = context.async();
  vertx.eventBus().consumer("the-address", msg -> {
    async2.complete();
  });
});
----

Async objects can also be used in _before_ or _after_ callbacks, it can be very convenient in a _before_ callback
to implement a setup that depends on one or several asynchronous results:

.Async start an http server before test cases
[source,java]
----
suite.before(context -> {
  Async async = context.async();
  HttpServer server = vertx.createHttpServer();
  server.requestHandler(requestHandler);
  server.listen(8080, ar -> {
    context.assertTrue(ar.succeeded());
    async.complete();
  });
});
----

[[reporting]]
== Running

When a test suite is created, it won't be executed until the `link:apidocs/io/vertx/ext/unit/TestSuite.html#run--[run]` method
is called.

.Running a test suite
[source,java]
----
suite.run();
----

The test suite can also be ran with a specified `Vertx` instance:

.Provides a Vertx instance to run the test suite
[source,java]
----
suite.run(vertx);
----

When running with a `Vertx` instance, the test suite is executed using the Vertx event loop, see the <<eventloop>>
section for more details.

=== Test suite completion

No assumptions can be made about when the test suite will be completed, and if some code needs to be executed
after the test suite, it should either be in the test suite _after_ callback or as callback of the
`link:apidocs/io/vertx/ext/unit/TestCompletion.html[TestCompletion]`:

.Test suite execution callback
[source,java]
----
TestCompletion completion = suite.run(vertx);
completion.handler(ar -> {
  if (ar.succeeded()) {
    System.out.println("Test suite passed!");
  } else {
    System.out.println("Test suite failed:");
    ar.cause().printStackTrace();
  }
});
----

The `TestCompletion` object provides also a `link:apidocs/io/vertx/ext/unit/TestCompletion.html#resolve-io.vertx.core.Future-[resolve]` method that
takes a `Future` object, this `Future` will be notified of the test suite execution:

.Resolving the start Future with the test suite
[source,java]
----
TestSuite suite = TestSuite.create("my_test_suite");
suite.test("my_test_case", context -> {
  // Do something
});
suite.run().resolve(startFuture);
----

This allow to easily create a _test_ verticle whose deployment is the test suite execution, allowing the
code that deploys it to be easily aware of the success or failure.

=== Time out

Each test case of a test suite must execute before a certain timeout is reached. The default timeout is
of _2 minutes_, it can be changed using _test options_:

.Setting the test suite timeout
[source,java]
----
TestOptions options = new TestOptions().setTimeout(10000);

// Run with a 10 seconds time out
suite.run(options);
----

[[event_loop]]
=== Event loop

Vertx Unit execution is a list of tasks to execute, the execution of each task is driven by the completion
of the previous task. These tasks should leverage Vert.x event loop when possible but that depends on the
current execution context (i.e the test suite is executed in a `main` or embedded in a `Verticle`) and
wether or not a `Vertx` instance is configured.

The `link:apidocs/io/vertx/ext/unit/TestOptions.html#setUseEventLoop-java.lang.Boolean-[setUseEventLoop]` configures the usage of the event
loop:

.Event loop usage
|===
| | useEventLoop:null | useEventLoop:true | useEventLoop:false

| `Vertx` instance
| use vertx event loop
| use vertx event loop
| force no event loop

| in a `Verticle`
| use current event loop
| use current event loop
| force no event loop

| in a _main_
| use no event loop
| raise an error
| use no event loop

|===

The default `useEventLoop` value is `null`, that means that it will uses an event loop when possible and fallback
to no event loop when no one is available.

== Reporting

Reporting is an important piece of a test suite, Vertx Unit can be configured to run with different kind
of reporters.

By default no reporter is configured, when running a test suite, _test options_ can be provided to
configure one or several:

.Using the console reporter and as a junit xml file
[source,java]
----
suite.run(new TestOptions().
        addReporter(new ReportOptions().
            setTo("console")).
        addReporter(new ReportOptions().
            setTo("file").
            setAt("report.xml").
            setFormat("junit"))
);
----

=== Console reporting

Reports to the JVM `System.out` and `System.err`:

to::
_console_
format::
_simple_ or _junit_

=== File reporting

Reports to a file, a `Vertx` instance must be provided:

to::
_file_
at::
the file name
format::
_simple_ or _junit_

=== Log reporting

Reports to a logger, a `Vertx` instance must be provided:

to::
_log_
at::
the logger name

=== Event bus reporting

Reports events to the event bus, a `Vertx` instance must be provided:

to::
_bus_
at::
the event bus address to which events will be sent

It allow to decouple the execution of the test suite from the reporting.

The messages sent over the event bus can be collected by the `link:apidocs/io/vertx/ext/unit/collect/EventBusCollector.html[EventBusCollector]`
and achieve custom reporting:

[source,java]
----
EventBusCollector collector = EventBusCollector.create(
    vertx,
    new ReportingOptions().addReporter(
        new ReportOptions().setTo("file").setAt("report.xml").setFormat("junit")));

collector.register("the-address");
----

== Java language integration

The Java language provides classes and it is possible to create test suites directly from Java classes with the
following mapping rules:

The  argument methods are inspected and the public, non static methods
with `link:apidocs/io/vertx/ext/unit/TestContext.html[TestContext]` parameter are retained and mapped to a Vertx Unit test suite
via the method name:

* `before` : before callback
* `after` : after callback
* `beforeEach` : beforeEach callback
* `afterEach` : afterEach callback
*  when the name starts with _test_ : test case callback named after the method name

.Test suite written using a Java class
[source,java]
----
public class MyTestSuite {

  public void testSomething(Test test) {
    test.assertFalse(false);
  }
}
----

This class can be turned into a Vertx test suite easily:

.Create a test suite from a Java object
[source,java]
----
TestSuite suite = TestSuite.create(new MyTestSuite());
----

== Junit integration

Although Vertx Unit is polyglot and not based on JUnit, it is possible to run a Vertx Unit test suite or a test case
from JUnit, allowing you to integrate your tests with JUnit and your build system or IDE.

.Run the test suite as a JUnit test suite
[source,java]
----
RunWith(AllTests.class)
public class JUnitTestSuite {

  public static TestSuite suite() {
    return io.vertx.ext.unit.TestSuite.create("my_test_suite").
      test("my_test_case", context -> {
        context.assertTrue(true);
      }).
      test("my_test", context -> {
        // Test 2
      }).toJUnitSuite();
  }
}
----

This can be combined with the Java integration seen earlier:

.Run the test suite as a JUnit test suite
[source,java]
----
RunWith(AllTests.class)
public class MyTestSuite {

  public static TestSuite suite() {
    return io.vertx.ext.unit.TestSuite.create(new MyTestSuite()).toJUnitSuite();
  }

  public void testSomething(Test test) {
    test.assertFalse(false);
  }
}
----

A single test case can also be executed with a `link:apidocs/io/vertx/ext/unit/TestCase.html[TestCase]`:

.Run a test case in a JUnit test
[source,java]
----
TestCase.
  create("my_test_case", context -> {
    context.assertTrue(true);
  }).
  awaitSuccess(); // <1>
----
<1> Block until the test case is executed